removed-line-endings

diff --git a/.local/bin/cp-g++ b/.local/bin/cp-g++
--- a/.local/bin/cp-g++
+++ b/.local/bin/cp-g++
@@ -5,16 +5,16 @@ shopt -s nullglob
 candidates=(/opt/homebrew/bin/g++-[0-9]* /usr/local/bin/g++-[0-9]*)
 
 if ((${#candidates[@]} == 0)); then
-    echo "cp-g++: GNU C++ compiler missing; run brew install gcc" >&2
-    exit 127
+  echo "cp-g++: GNU C++ compiler missing; run brew install gcc" >&2
+  exit 127
 fi
 
 latest=$(
-    printf '%s\n' "${candidates[@]}" |
-        awk -F'g\\+\\+-' '{ print $NF "\t" $0 }' |
-        sort -n |
-        tail -n 1 |
-        cut -f2-
+  printf '%s\n' "${candidates[@]}" |
+      awk -F'g\\+\\+-' '{ print $NF "\t" $0 }' |
+      sort -n |
+      tail -n 1 |
+      cut -f2-
 )
 
 exec "$latest" "$@"
